services:
  db:
    container_name: taxidi-db
    image: postgres:17
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file: .env

  pgbouncer:
    container_name: taxidi_pgbouncer
    image: edoburu/pgbouncer
    restart: always
    depends_on:
      - db
    ports:
      - '6432:6432'
    env_file: .env

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: taxidi_api
    depends_on:
      - pgbouncer
    ports:
      - '8080:8080'

volumes:
  postgres_data:
