// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';
const NODE_ENV = env('NODE_ENV');

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: NODE_ENV === "production" ? env('DATABASE_URL'): env('LOCAL_DATABASE_URL')
    // shadowDatabaseUrl: env("DIRECT_DATABASE_URL")
  },
});
