services:
  db:
    container_name: taxidi-db
    image: postgres:17
    expose:
      - 5432
    volumes:
      - taxidi_volume:/var/lib/postgresql/data

    env_file: ../.env
    networks:
      - taxidi_network

  pgbouncer:
    container_name: taxidi-pgbouncer
    image: edoburu/pgbouncer
    restart: always
    depends_on:
      - db
    expose:
      - 5432
    env_file: ../.env
    networks:
      - taxidi_network
  
  redis:
    expose:
      - 6379

  api:
    build:
      context: ../
      dockerfile: ./apps/api/docker/Dockerfile
    depends_on:
      - pgbouncer
    expose:
      - 8080
    networks:
      - taxidi_network

  nginx:
    container_name: taxidi-proxy
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - '80:80'
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - taxidi_network
