services:
  db:
    ports:
      - '5432:5432'
    volumes:
      - taxidi_volume:/var/lib/postgresql/data

    env_file: ../.env

  pgbouncer:
    depends_on:
      - db
    ports:
      - '6432:5432'
    env_file: ../.env

  redis:
    ports:
      - '6379:6379'

  # api:
  #   container_name: api-server
  #   build:
  #     context: ../
  #     dockerfile: ./apps/api/Dockerfile.dev
  #   depends_on:
  #     - pgbouncer
  #   ports:
  #     - '80:8080'
  #   volumes:
  #     - ../apps/api/src:/taxidi/apps/api/src
  #     - /taxidi/node_modules
