name: taxidi-image
services:
  db:
    container_name: taxidi-db
    image: postgres:17

  pgbouncer:
    container_name: taxidi-pgbouncer
    image: edoburu/pgbouncer
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: taxidi-redis
    volumes:
      - taxidi_redis_data:/data

  # api:
  #   restart: unless-stopped

volumes:
  taxidi_volume:
    external: true
  taxidi_redis_data:

networks:
  taxidi_network:
