FROM node:22-alpine

WORKDIR /taxidi

RUN npm install -g pnpm

COPY . .

RUN pnpm install

# build only api dependencies
# RUN pnpm --filter @taxidi/api... build

WORKDIR /taxidi/apps/api

EXPOSE 8080

CMD ["pnpm", "run", "dev"]